

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --workers 4 --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - .:/usr/src/app
      - static_volume_live:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network_live

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume_live:/usr/src/app/staticfiles
    depends_on:
      - web
    networks:
      - app-network_live

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: p24_db
      POSTGRES_USER: p24_db_usr
      POSTGRES_PASSWORD: p24_db_pwd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: # not necessary to expose the port
       - "5432:5432"
    networks:
      - app-network_live

volumes:
  static_volume_live:
  postgres_data:  

networks:
  app-network_live:
    name: app-network_live
    driver: bridge
