# Generated by Django 4.2.19 on 2025-03-26 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="users",
            field=models.ManyToManyField(
                default=1, related_name="category", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="users",
            field=models.ManyToManyField(
                default=1, related_name="quiz", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="users",
            field=models.ManyToManyField(
                default=1, related_name="subjects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
