# Generated by Django 4.2.19 on 2025-03-26 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_category_users_quiz_users_subject_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="users",
            field=models.ManyToManyField(
                related_name="category", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="users",
            field=models.ManyToManyField(
                related_name="quiz", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="users",
            field=models.ManyToManyField(
                related_name="subjects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
