# Generated by Django 4.2.19 on 2025-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_category_users_alter_quiz_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject", name="name", field=models.CharField(max_length=255),
        ),
    ]
