# Generated by Django 4.2.19 on 2025-04-22 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_group_studentlist_groupquiz_groupinvitation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_answered", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(model_name="groupquiz", name="is_answered",),
        migrations.RemoveField(model_name="groupquiz", name="score",),
        migrations.DeleteModel(name="StudentList",),
        migrations.AddField(
            model_name="userquizresult",
            name="group_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_results",
                to="home.groupquiz",
            ),
        ),
        migrations.AddField(
            model_name="userquizresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
