# Generated by Django 4.2.19 on 2025-04-22 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_userquizresult_remove_groupquiz_is_answered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupquiz",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
